export const weaponsMap = {
    CLASSIC: 0,
    SHORTY: 1,
    FRENZY: 2,
    GHOST: 3,
    SHERIFF: 4,
    STINGER: 5,
    SPECTRE: 6,
    BULLDOG: 7,
    GUARDIAN: 8,
    PHANTOM: 9,
    VANDAL: 10,
    BUCKY: 11,
    JUDGE: 12,
    ARES: 13,
    ODIN: 14,
    MARSHAL: 15,
    OPERATOR: 16,
}
